%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.8.0

-ifndef(kafka_proto).
-define(kafka_proto, true).

-define(kafka_proto_gpb_version, "4.8.0").

-ifndef('MQTT_PB_H').
-define('MQTT_PB_H', true).
-record(mqtt,
        {mountpoint             :: iodata(),        % = 1
         client_id              :: iodata(),        % = 2
         topic                  :: iodata(),        % = 3
         payload                :: iodata()         % = 4
        }).
-endif.

-endif.
